"""Alert model for cluster and other notifications."""

from datetime import datetime, timezone
from enum import Enum
from typing import Optional

from sqlalchemy import DateTime, Integer, String
from sqlalchemy.orm import Mapped, mapped_column

from tidesight.db.database import Base


class AlertType(str, Enum):
    """Types of alerts generated by the system."""

    CLUSTER = "cluster"


class AlertSeverity(str, Enum):
    """Severity levels for alerts."""

    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class Alert(Base):
    """SQLAlchemy model for system alerts.

    Stores cluster alerts when multiple large vessels target the same
    tidal window.

    Attributes:
        id: Alert identifier (UUID string).
        alert_type: Type of alert (e.g., cluster).
        severity: Alert severity level.
        message: Human-readable alert message.
        vessel_mmsis: Comma-separated list of involved vessel MMSIs.
        target_window: The tidal window causing the alert.
        created_at: When alert was created.
        resolved_at: When alert was resolved (null if active).
    """

    __tablename__ = "alerts"

    id: Mapped[str] = mapped_column(String(50), primary_key=True)
    alert_type: Mapped[str] = mapped_column(String(20), nullable=False)
    severity: Mapped[str] = mapped_column(String(20), nullable=False)
    message: Mapped[str] = mapped_column(String(500), nullable=False)
    vessel_mmsis: Mapped[str] = mapped_column(String(200), nullable=False)
    target_window: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )
    resolved_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    @property
    def is_active(self) -> bool:
        """Check if alert is still active (not resolved)."""
        return self.resolved_at is None

    @property
    def vessel_list(self) -> list[int]:
        """Parse vessel_mmsis string into list of integers."""
        if not self.vessel_mmsis:
            return []
        return [int(mmsi) for mmsi in self.vessel_mmsis.split(",")]

    @classmethod
    def create_cluster_alert(
        cls,
        alert_id: str,
        vessels: list[int],
        window: datetime,
        severity: AlertSeverity = AlertSeverity.WARNING,
    ) -> "Alert":
        """Create a cluster alert for multiple vessels in same window.

        Args:
            alert_id: Unique alert identifier.
            vessels: List of vessel MMSIs in the cluster.
            window: Target tidal window.
            severity: Alert severity level.

        Returns:
            New Alert instance (not yet persisted).
        """
        vessel_count = len(vessels)
        window_str = window.strftime("%H:%M")
        message = f"{vessel_count} large vessels targeting {window_str} tidal window"

        return cls(
            id=alert_id,
            alert_type=AlertType.CLUSTER.value,
            severity=severity.value,
            message=message,
            vessel_mmsis=",".join(str(mmsi) for mmsi in vessels),
            target_window=window,
        )
